[package]
name = "drcode"
version = "0.1.2"
authors = ["Your Name <your.email@example.com>"]
edition = "2021"
description = "A Rust package for easy integration with DrCode error tracking"
license = "MIT"

[dependencies]
sentry = "0.31.0"
thiserror = "1.0"
